services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ..:/home/node/src
    depends_on:
      - postgre
    tty: true
  postgre:
    image: pgvector/pgvector:pg16
    volumes:
      - postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: /usr/bin/pg_isready -h 'localhost'

volumes:
  postgre:
    driver_opts:
      type: tmpfs
      device: tmpfs
